#Deploy configmap for DB Host, User, Port, Database and App Colour
apiVersion: v1

kind: ConfigMap

metadata:

  name: app-config

data:

  DB_USER: root

  DB_HOST: "db-service"

  DB_PORT: "3306"

  DATABASE: "employees"
  
  APP_COLOR: "blue"
  
  background_image_location: https://clo835-finalproject-group1buckett.s3.us-east-1.amazonaws.com/ilovecats.jpeg?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEGsaCXVzLWVhc3QtMiJIMEYCIQDdDg3w9rWNNywXyw5l5zHcqkBp%2BsIlsMil4g3w61ilKQIhAIb6Vom0bT%2Bimz8yXjEpgUuQG7IaKq2A5ZDWPwdfY49LKvcCCGQQABoMNDQ4ODcwNzIxMjMwIgwiivhWtB8q8BBf88oq1AL8AEcX6PIEA4hNpYyH1uZCY3aJmuhzCzuoKK71ryNBCs5uTzGqBmBJjezOuEht5HbZy1bp1ayRZ0mSeoRxnarLwtcMKTUCoqvUdXWRQQjFJbgixRdwo5Mp%2FnY0bNhKy4SwrzvNeYezHv%2Bvrg3BJcRejggVA9AUBfJ%2FHsbrhUxtFknK8zsTNgQCn91nQqufv04y26T4ILLhniqVG30XwKJQ7QZ%2F%2B0F8FnXrdpEK2tAH2yPB6%2F4YI8F57x%2BJYVmb89rYsn3qAOXWWNOZrGm7GkkXwFAmagUCCBx4q%2FeNs5UvQqCb%2FhzjTF1cjUdVRWIuKdVrX2uE8AojM4Aw%2F31JBlIuqVl8PhzAKj%2BekzPqnvRM0sY%2FUOm0Iv8foF2PAo0lX7%2BjvkZ%2FfExT4rmwgKZ8MisLJl0%2BuFm79aKENZAHyk6pzwxgb0%2FNWXnRTf6IEGxYk1R3WxzuMPLG%2B6EGOoYCgMK0CjBJ6KWDtLRK%2BbjXRquFqPSy96sr4W%2BuQ1opZurdC4pQ%2Bk6VPa8a4RT3CYgVKHYihuBG5fkP4lD9mw7Q1fvYBuOtVcdpj0pgUYe%2FgcNKKEDo0H2XiJvaLaH6hPcUYQqXqXYJvA9Y5z2CgQ4cMN2wTNUOm7%2B0EEJfrDon5ZRRMqejrGifJeOpJ8on29lBPsck3aoQhG8DZe2zrx30iUOuc%2FnqdoO%2BPtZZFt7F5WHQL3zNBQOIh7pN%2FlowEtP%2BuKb3%2Fsnm3cdNAZ6VsLfXlhwTm1pvwyJWnafIuKwOrxIzx1yLJaSoy2xYq3Bs%2FVp9%2FLK0QfW%2BdGZHyQE%2Bcj4CmKoogyblyw%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230418T210530Z&X-Amz-SignedHeaders=host&X-Amz-Expires=720&X-Amz-Credential=ASIAWRAWHU3HCCHQROU7%2F20230418%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=fb729d26550ed16207fbf9e0d06518ce454e81dd0eece53e2f6e98787b7b9404
  
  
