#Deploy configmap for DB Host, User, Port, Database and App Colour
apiVersion: v1

kind: ConfigMap

metadata:

  name: app-config

data:

  DB_USER: root

  DB_HOST: "db-service"

  DB_PORT: "3306"

  DATABASE: "employees"
  
  background_image_location: https://clo835-finalproject-2023.s3.us-east-1.amazonaws.com/ilovedogs.jpg?response-content-disposition=inline&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEDIaCXVzLWVhc3QtMiJHMEUCIHKJqaBFd8sRGaiiGxHPhP%2FsXbupjsA8s4A%2F13vwL9xIAiEAjqMbR8ISjzPo3YAmcKe7JSecNtB6rjE5DRYn%2ByikXYsq9AIILBAAGgw3NDA1ODA4OTQ1NDAiDNtnT1fRrPPqLZ7TIirRAjgFDpu%2FMd1%2FIcqCJ26XSzoC98urNLnpgqYay3Ldd0Refn9pq892JEiXM%2FHPQaxm%2FtjE30DxYJGg2tWjphRr1KZMZqNkKXUcpj7T91ZUOzduziRNe9G8yAWwPHXJoALlUMjayf0Mlkrj7BYwEkhDGpmEr1d8NMwfFFxbqEKqgxeebO%2BQmu%2BrCcuR4EC%2BQcPsfMQ1bwAL4yHPRaiXlBDGneUGWO5k7wACX2lyLc9x2spVStXdv0Mfh7kEbvw6JUszcOBzdteTblyjdhl%2F%2FXkLmmEygUyRSXiQ%2FmGQ%2FZxF15CUzH2%2Bt4%2Boq7qD7DGtK1s2Cvk9OHMwSdU%2FQMrmriIUiGnNs2qICayQvnOvRagZKi%2FbFIiCTMR0ZnxnyqmFcVvGup2JozUSdEpd5vo1IhdJ1we3peffPPAnm3Rm%2BKyfhrZRfnERFJ%2BGCQun4v%2BeNlLWUr0wg5vvoQY6hwJgzhlrm97PjJlwNy6FmF0djVDkyDMeBsAijErArDmvK0FZ1eaHzXdObtyWkn54iDcuAN9rw8lAogNlZyLvPEm5bAVdqje%2BqACKBItShkwZ00w4hL6tpmlTej4S8bGArQvrnzCBlDDXB7GBhvrfDBL6zUcUvT11G2%2BkoJP3N%2FywJLIuc8xEqWvhuKqQyc9F09yQk4JEtMJmpcbwcfGd9BFN1zGcD7Qn2DiSH%2BtZaR7UwYSkMf3GzqZlNqDlZRh%2BBpRn89FOHlfQjlLSauLPByENvyF%2BET3Ql2tbXMntT6e80VB99pqB3RiNMCjYrEizqgdZmez9KPqIKmYAnXuvvmKzgvlXKJMWrg%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230416T133033Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=ASIA2Y3QPU5GK3G6BNHD%2F20230416%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e759ec0eed4767e3a09d56e881e66c44bbd6fe959ac7b7970fad35b29070b7c3