#Deploy secret for db password and app color
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secretkey
type: Opaque
data:
  password: ZWRtrY2=
type: kubernetes.io/basic-auth
stringData:
  color: lime