  name: app-deployment
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: app
          image: 718227961166.dkr.ecr.us-east-1.amazonaws.com/webapp_repo:v0.211
          ports:
            - containerPort: 81
          env:
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secretkey
                  key: password
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: BackgroundImageLocation
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: background_image_location
